import useToast from '../../hooks/useToast';
import { CP } from '../../data/clientPortal';

const fontBody = "'DM Sans', sans-serif";

export default function ClientReports({ report }) {
  const toast = useToast();
  if (!report) return null;

  const { title, period, summary, keyMetrics } = report;

  return (
    <section
      style={{
        backgroundColor: CP.surface,
        border: `1px solid ${CP.border}`,
        borderRadius: 12,
        padding: 24,
        marginBottom: 24,
      }}
    >
      <div style={{ display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between', flexWrap: 'wrap', gap: 12, marginBottom: 16 }}>
        <div>
          <h2 style={{ fontFamily: fontBody, fontSize: 18, fontWeight: 700, color: CP.text, margin: '0 0 4px' }}>
            {title}
          </h2>
          <span style={{ fontFamily: fontBody, fontSize: 13, color: CP.textSecondary }}>{period}</span>
        </div>
        <span
          style={{
            padding: '4px 10px',
            borderRadius: 6,
            fontSize: 11,
            fontFamily: fontBody,
            color: CP.primary,
            border: `1px solid ${CP.primary}40`,
          }}
        >
          Generated by ARIA
        </span>
      </div>
      {keyMetrics && (
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', gap: 16, marginBottom: 20 }}>
          <div>
            <div style={{ fontFamily: fontBody, fontSize: 11, color: CP.textSecondary, textTransform: 'uppercase', marginBottom: 4 }}>Demos</div>
            <div style={{ fontFamily: fontBody, fontSize: 20, fontWeight: 700, color: CP.text }}>{keyMetrics.demos}</div>
          </div>
          <div>
            <div style={{ fontFamily: fontBody, fontSize: 11, color: CP.textSecondary, textTransform: 'uppercase', marginBottom: 4 }}>Leads</div>
            <div style={{ fontFamily: fontBody, fontSize: 20, fontWeight: 700, color: CP.text }}>{keyMetrics.leads}</div>
          </div>
          <div>
            <div style={{ fontFamily: fontBody, fontSize: 11, color: CP.textSecondary, textTransform: 'uppercase', marginBottom: 4 }}>CPL</div>
            <div style={{ fontFamily: fontBody, fontSize: 20, fontWeight: 700, color: CP.text }}>{keyMetrics.cpl}</div>
          </div>
          <div>
            <div style={{ fontFamily: fontBody, fontSize: 11, color: CP.textSecondary, textTransform: 'uppercase', marginBottom: 4 }}>CTR</div>
            <div style={{ fontFamily: fontBody, fontSize: 20, fontWeight: 700, color: CP.text }}>{keyMetrics.ctr}</div>
          </div>
        </div>
      )}
      <p style={{ fontFamily: fontBody, fontSize: 14, color: CP.textSecondary, lineHeight: 1.6, margin: '0 0 16px' }}>
        {summary}
      </p>
      <button
        style={{
          padding: '10px 20px',
          borderRadius: 7,
          border: 'none',
          backgroundColor: CP.primary,
          color: '#fff',
          fontFamily: fontBody,
          fontSize: 14,
          fontWeight: 600,
          cursor: 'pointer',
        }}
        onClick={() => toast.success('Download started')}
      >
        Download PDF
      </button>
    </section>
  );
}
