import { useNavigate } from 'react-router-dom';
import useToast from '../../hooks/useToast';
import { C, F, R, S, btn, cardStyle } from '../../tokens';
import AgentFeed from '../../components/agents/AgentFeed';
import { IconCheck, IconCircleFilled, IconCircleEmpty, IconArrowRight } from '../../components/ui/Icons';

const NEEDS_REVIEW_MOCK = [
  { id: '1', type: 'Email Seq B — Step 3', contentId: 'CAMP-001-EMAIL-003', status: 'In Review', note: 'Badhon requested changes — Freya has revised' },
  { id: '2', type: 'LinkedIn Message — Cold CFO', contentId: 'CAMP-001-LI-001', status: 'Awaiting first review', note: 'Generated by Copywriter Agent · 3 hours ago' },
];
const CALENDAR_MOCK = [
  { label: 'Mon: Email step 3', status: 'done' },
  { label: 'Tue: LinkedIn post', status: 'scheduled' },
  { label: 'Wed: Blog: SEO art', status: 'pending' },
  { label: 'Thu: Ad copy refresh', status: 'pending' },
  { label: 'Fri: Client report', status: 'pending' },
];

export default function DashboardContentStrategist() {
  const navigate = useNavigate();
  const toast = useToast();

  return (
    <div style={{ padding: S[6], display: 'flex', flexDirection: 'column', gap: S[5], minHeight: '100%' }}>
      <div>
        <h1 style={{ fontFamily: F.display, fontSize: '22px', fontWeight: 800, color: C.textPrimary, margin: 0 }}>Content Pipeline</h1>
        <span style={{ fontFamily: F.body, fontSize: '13px', color: C.textSecondary }}>8 pieces in production · 3 need your review · 2 ready to ship</span>
      </div>
      <div>
        <h2 style={{ fontFamily: F.display, fontSize: '13px', fontWeight: 700, color: C.textMuted, textTransform: 'uppercase', margin: `0 0 ${S[3]}` }}>Needs Your Review</h2>
        <div style={{ display: 'flex', flexDirection: 'column', gap: S[3] }}>
          {NEEDS_REVIEW_MOCK.map((item) => (
            <div key={item.id} style={{ ...cardStyle, padding: S[4] }}>
              <div style={{ fontFamily: F.display, fontSize: '14px', fontWeight: 600, color: C.textPrimary }}>{item.type}</div>
              <div style={{ fontFamily: F.mono, fontSize: '11px', color: C.textMuted }}>{item.contentId}</div>
              <div style={{ fontFamily: F.body, fontSize: '12px', color: C.textSecondary }}>Status: {item.status} · {item.note}</div>
              <button style={{ ...btn.primary, fontSize: '12px', marginTop: S[3], display: 'inline-flex', alignItems: 'center', gap: S[1] }} onClick={() => toast.info('Review')}>Review & approve <IconArrowRight width={14} height={14} /></button>
            </div>
          ))}
        </div>
      </div>
      <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: S[5] }}>
        <div>
          <h2 style={{ fontFamily: F.display, fontSize: '13px', fontWeight: 700, color: C.textMuted, textTransform: 'uppercase', margin: `0 0 ${S[3]}` }}>Content Calendar (this week)</h2>
          <div style={{ ...cardStyle, padding: S[4] }}>
            {CALENDAR_MOCK.map((item, i) => (
              <div key={i} style={{ fontFamily: F.body, fontSize: '12px', color: C.textSecondary, marginBottom: S[1], display: 'flex', alignItems: 'center', gap: S[1] }}>
                {item.status === 'done' && <IconCheck color={C.primary} width={14} height={14} />}
                {item.status === 'scheduled' && <IconCircleFilled color={C.primary} width={8} height={8} />}
                {item.status === 'pending' && <IconCircleEmpty color={C.textMuted} width={14} height={14} />}
                {item.label}
              </div>
            ))}
            <button style={{ ...btn.ghost, fontSize: '12px', marginTop: S[2], display: 'inline-flex', alignItems: 'center', gap: S[1] }} onClick={() => navigate('/content')}>Full calendar <IconArrowRight width={14} height={14} /></button>
          </div>
        </div>
        <div>
          <h2 style={{ fontFamily: F.display, fontSize: '13px', fontWeight: 700, color: C.textMuted, textTransform: 'uppercase', margin: `0 0 ${S[3]}` }}>Brand Health</h2>
          <div style={{ ...cardStyle, padding: S[4] }}>
            <div style={{ fontFamily: F.body, fontSize: '12px', color: C.textSecondary, display: 'flex', alignItems: 'center', gap: S[1] }}><IconCheck color={C.primary} width={14} height={14} /> Voice consistency: 94%</div>
            <div style={{ fontFamily: F.body, fontSize: '12px', color: C.textSecondary, display: 'flex', alignItems: 'center', gap: S[1] }}><IconCheck color={C.primary} width={14} height={14} /> ICP alignment: 87%</div>
            <div style={{ fontFamily: F.body, fontSize: '12px', color: C.textSecondary, display: 'flex', alignItems: 'center', gap: S[1] }}><IconCheck color={C.primary} width={14} height={14} /> Tone score: On-brand</div>
            <div style={{ fontFamily: F.body, fontSize: '12px', color: C.textMuted, marginTop: S[3] }}>Last 7 days: 14 pieces generated, 12 approved, 2 in revision</div>
            <button style={{ ...btn.ghost, fontSize: '12px', marginTop: S[2], display: 'inline-flex', alignItems: 'center', gap: S[1] }} onClick={() => navigate('/content')}>View all content <IconArrowRight width={14} height={14} /></button>
          </div>
        </div>
      </div>

      {/* Agent Activity Feed (Content Strategist-relevant) */}
      <div>
        <h2 style={{ fontFamily: F.display, fontSize: '13px', fontWeight: 700, color: C.textMuted, textTransform: 'uppercase', margin: `0 0 ${S[3]}` }}>Agent Activity</h2>
        <AgentFeed limit={6} />
      </div>
    </div>
  );
}
