/**
 * Weekly Executive Digest — Session 5.
 * DigestHeader; ARIA narrative; 6-block KPI strip; Anomalies; 3 priority actions; performance mini-charts; DigestScheduleConfig slide-over.
 */
import { useState } from 'react';
import useToast from '../hooks/useToast';
import {
  DIGEST_WEEK,
  DIGEST_KPIS,
  DIGEST_NARRATIVE,
  DIGEST_ANOMALIES,
  DIGEST_PRIORITY_ACTIONS,
  DIGEST_DELIVERY,
  DIGEST_MINI_CHARTS,
  DIGEST_SCHEDULE_DEFAULT,
} from '../data/digestMock';
import DigestHeader from '../components/digest/DigestHeader';
import DigestKPIBlock from '../components/digest/DigestKPIBlock';
import DigestNarrativeSection from '../components/digest/DigestNarrativeSection';
import AnomalyAlertRow from '../components/digest/AnomalyAlertRow';
import PriorityActionCard from '../components/digest/PriorityActionCard';
import DigestMiniChart from '../components/digest/DigestMiniChart';
import DigestScheduleConfig from '../components/digest/DigestScheduleConfig';
import { C, F, R, S, btn } from '../tokens';
import { useAgent } from '../hooks/useAgent';
import AgentThinking from '../components/agents/AgentThinking';
import AgentWorkflowVisualizer from '../components/agents/AgentWorkflowVisualizer';

/* ─── Digest agent section attribution ───────────────────── */
const DIGEST_AGENT_ATTRIBUTION = {
  narrative: { agent: 'Copywriter', label: 'Narrative polished by Copywriter' },
  kpis: { agent: 'Analyst', label: 'Data compiled by Analyst' },
  anomalies: { agent: 'Analyst', label: 'Anomalies detected by Analyst' },
  actions: { agent: 'Strategist', label: 'Recommendations by Strategist' },
  charts: { agent: 'Analyst', label: 'Trends analyzed by Analyst' },
};

export default function WeeklyExecutiveDigest() {
  const toast = useToast();
  const [scheduleOpen, setScheduleOpen] = useState(false);
  const [weekOffset, setWeekOffset] = useState(0);
  const analyst = useAgent('analyst');

  /* Agent workflow state */
  const [digestGenerating, setDigestGenerating] = useState(false);
  const [digestWorkflow, setDigestWorkflow] = useState(null);
  const [digestGenerated, setDigestGenerated] = useState(false);

  const handlePrevWeek = () => setWeekOffset((o) => o - 1);
  const handleNextWeek = () => setWeekOffset((o) => o + 1);
  const handleForward = () => toast.info('Forward (mock).');
  const handleDownload = () => toast.success('Download started.');
  const handleConfigure = () => setScheduleOpen(true);
  const handleScheduleSave = (config) => {
    toast.success('Digest schedule saved.');
    setScheduleOpen(false);
  };
  const handleAnomalyView = (a) => toast.info(`View: ${a.title}`);
  const handlePriorityAction = (action) => toast.info(action.actionLabel);

  const handleGenerateDigest = async () => {
    setDigestGenerating(true);
    setDigestGenerated(false);

    /* Step 1: Analyst gathers data */
    setDigestWorkflow({
      title: 'Generating Executive Digest',
      steps: [
        { agentId: 'analyst', label: 'Gathering data', status: 'active' },
        { agentId: 'strategist', label: 'Generating recommendations', status: 'pending' },
        { agentId: 'copywriter', label: 'Polishing narrative', status: 'pending' },
      ],
    });

    await new Promise((r) => setTimeout(r, 1500));

    /* Step 2: Strategist recommendations */
    setDigestWorkflow({
      title: 'Generating Executive Digest',
      steps: [
        { agentId: 'analyst', label: 'Gathering data', status: 'done' },
        { agentId: 'strategist', label: 'Generating recommendations', status: 'active' },
        { agentId: 'copywriter', label: 'Polishing narrative', status: 'pending' },
      ],
    });

    await new Promise((r) => setTimeout(r, 1500));

    /* Step 3: Copywriter polish */
    setDigestWorkflow({
      title: 'Generating Executive Digest',
      steps: [
        { agentId: 'analyst', label: 'Gathering data', status: 'done' },
        { agentId: 'strategist', label: 'Generating recommendations', status: 'done' },
        { agentId: 'copywriter', label: 'Polishing narrative', status: 'active' },
      ],
    });

    await new Promise((r) => setTimeout(r, 1200));

    /* Done */
    setDigestWorkflow({
      title: 'Executive Digest Generated',
      steps: [
        { agentId: 'analyst', label: 'Gathering data', status: 'done' },
        { agentId: 'strategist', label: 'Generating recommendations', status: 'done' },
        { agentId: 'copywriter', label: 'Polishing narrative', status: 'done' },
      ],
    });

    setDigestGenerating(false);
    setDigestGenerated(true);
    toast.success('Executive digest generated by 3-agent workflow.');
  };

  return (
    <div style={{ minHeight: '100%', backgroundColor: C.bg, padding: S[6] }}>

      {/* Generate digest button + workflow */}
      <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: S[4] }}>
        <div />
        <button
          type="button"
          onClick={handleGenerateDigest}
          disabled={digestGenerating}
          style={{ ...btn.primary, opacity: digestGenerating ? 0.6 : 1 }}
        >
          {digestGenerating ? 'Generating...' : 'Generate digest'}
        </button>
      </div>

      {/* Agent workflow visualizer */}
      {digestWorkflow && (
        <div style={{ marginBottom: S[5] }}>
          <AgentWorkflowVisualizer workflow={digestWorkflow} />
        </div>
      )}

      {/* Agent thinking indicator */}
      {digestGenerating && (
        <div style={{ marginBottom: S[4] }}>
          <AgentThinking agentId="analyst" task="Orchestrating digest generation: Analyst > Strategist > Copywriter" />
        </div>
      )}

      <DigestHeader
        weekLabel={DIGEST_WEEK.label}
        onPrevWeek={handlePrevWeek}
        onNextWeek={handleNextWeek}
        deliveryStatus={DIGEST_DELIVERY.status}
        deliveredAt={DIGEST_DELIVERY.deliveredAt}
        onForward={handleForward}
        onDownload={handleDownload}
        onConfigure={handleConfigure}
      />

      <div style={{ marginTop: S[6] }}>
        {digestGenerated && (
          <div style={{ display: 'flex', alignItems: 'center', gap: S[2], marginBottom: S[2] }}>
            <span style={{ fontFamily: F.mono, fontSize: '10px', fontWeight: 700, color: C.primary, textTransform: 'uppercase', backgroundColor: C.primaryGlow, padding: `1px ${S[2]}`, borderRadius: R.sm }}>{DIGEST_AGENT_ATTRIBUTION.narrative.label}</span>
          </div>
        )}
        <DigestNarrativeSection narrative={DIGEST_NARRATIVE} />
      </div>

      <div style={{ display: 'flex', alignItems: 'center', gap: S[3], margin: `${S[6]} 0 ${S[4]} 0` }}>
        <div style={{ fontFamily: F.display, fontSize: '16px', fontWeight: 700, color: C.textPrimary }}>
          Key metrics
        </div>
        {digestGenerated && (
          <span style={{ fontFamily: F.mono, fontSize: '10px', fontWeight: 700, color: C.primary, textTransform: 'uppercase', backgroundColor: C.primaryGlow, padding: `1px ${S[2]}`, borderRadius: R.sm }}>{DIGEST_AGENT_ATTRIBUTION.kpis.label}</span>
        )}
      </div>
      <div
        style={{
          display: 'grid',
          gridTemplateColumns: 'repeat(6, 1fr)',
          gap: S[4],
          marginBottom: S[6],
        }}
      >
        {DIGEST_KPIS.map((kpi) => (
          <DigestKPIBlock
            key={kpi.id}
            name={kpi.name}
            value={kpi.value}
            vsLastWeek={kpi.vsLastWeek}
            vsTarget={kpi.vsTarget}
            trend={kpi.trend}
          />
        ))}
      </div>

      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: S[4], marginBottom: S[6] }}>
        {DIGEST_MINI_CHARTS.map((chart) => (
          <div
            key={chart.metric}
            style={{
              padding: S[4],
              backgroundColor: C.surface,
              border: `1px solid ${C.border}`,
              borderRadius: R.card,
            }}
          >
            <div style={{ fontFamily: F.body, fontSize: '12px', fontWeight: 600, color: C.textSecondary, marginBottom: S[2] }}>
              {chart.metric} (7d)
            </div>
            <DigestMiniChart id={chart.metric} values={chart.values} />
          </div>
        ))}
      </div>

      <div style={{ display: 'flex', alignItems: 'center', gap: S[3], margin: `0 0 ${S[4]} 0` }}>
        <div style={{ fontFamily: F.display, fontSize: '16px', fontWeight: 700, color: C.textPrimary }}>
          Anomalies
        </div>
        {digestGenerated && (
          <span style={{ fontFamily: F.mono, fontSize: '10px', fontWeight: 700, color: C.primary, textTransform: 'uppercase', backgroundColor: C.primaryGlow, padding: `1px ${S[2]}`, borderRadius: R.sm }}>{DIGEST_AGENT_ATTRIBUTION.anomalies.label}</span>
        )}
      </div>
      <div style={{ display: 'flex', flexDirection: 'column', gap: S[3], marginBottom: S[6] }}>
        {DIGEST_ANOMALIES.map((a) => (
          <AnomalyAlertRow key={a.id} anomaly={a} onView={handleAnomalyView} />
        ))}
      </div>

      <div style={{ display: 'flex', alignItems: 'center', gap: S[3], margin: `0 0 ${S[4]} 0` }}>
        <div style={{ fontFamily: F.display, fontSize: '16px', fontWeight: 700, color: C.textPrimary }}>
          Priority actions
        </div>
        {digestGenerated && (
          <span style={{ fontFamily: F.mono, fontSize: '10px', fontWeight: 700, color: C.primary, textTransform: 'uppercase', backgroundColor: C.primaryGlow, padding: `1px ${S[2]}`, borderRadius: R.sm }}>{DIGEST_AGENT_ATTRIBUTION.actions.label}</span>
        )}
      </div>
      <div style={{ display: 'flex', flexDirection: 'column', gap: S[3], marginBottom: S[6] }}>
        {DIGEST_PRIORITY_ACTIONS.map((action) => (
          <PriorityActionCard
            key={action.id}
            number={action.number}
            description={action.description}
            actionLabel={action.actionLabel}
            hasDraft={action.hasDraft}
            onAction={() => handlePriorityAction(action)}
          />
        ))}
      </div>

      <DigestScheduleConfig
        initial={DIGEST_SCHEDULE_DEFAULT}
        open={scheduleOpen}
        onClose={() => setScheduleOpen(false)}
        onSave={handleScheduleSave}
      />
    </div>
  );
}
