export const ADDONS = [
  {
    id: 'extra_credits_10k',
    name: 'Extra Credits Pack',
    description: '10,000 additional agent credits. Rolls over for 30 days.',
    price: 99,
    type: 'one_time',
    availableOn: ['starter', 'growth', 'scale', 'agency'],
    icon: 'zap',
  },
  {
    id: 'extra_workspace',
    name: 'Extra Client Workspace',
    description: 'One additional client workspace with full campaign access.',
    price: 99,
    type: 'monthly',
    availableOn: ['starter', 'growth', 'scale'],
    icon: 'briefcase',
  },
  {
    id: 'extra_seats_5pack',
    name: 'Team Seat 5-Pack',
    description: '5 additional team member seats.',
    price: 49,
    type: 'monthly',
    availableOn: ['growth', 'scale'],
    icon: 'users',
  },
  {
    id: 'intent_data_boost',
    name: 'Intent Data Boost',
    description: 'Person-level website deanonymization + G2 intent signals.',
    price: 299,
    type: 'monthly',
    availableOn: ['growth', 'scale', 'agency'],
    icon: 'eye',
  },
  {
    id: 'custom_agent_build',
    name: 'Custom Agent Build',
    description: 'Bespoke AI agent trained on your specific workflow. Includes hosting.',
    price: 1500,
    type: 'one_time',
    monthlyHosting: 299,
    availableOn: ['scale', 'agency'],
    icon: 'cpu',
  },
  {
    id: 'aria_voice_expansion',
    name: 'ARIA Voice Expansion',
    description: '+500 call minutes per month for ARIA Voice AI.',
    price: 199,
    type: 'monthly',
    availableOn: ['scale', 'agency'],
    icon: 'phone',
  },
  {
    id: 'data_warehouse_sync',
    name: 'Data Warehouse Sync (Bi-Directional)',
    description: 'Bi-directional sync with Snowflake, BigQuery, or Redshift.',
    price: 499,
    type: 'monthly',
    availableOn: ['growth', 'scale', 'agency'],
    icon: 'database',
  },
  {
    id: 'executive_reports',
    name: 'Executive Reports (White-Glove)',
    description: 'Human-reviewed monthly strategy reports per client. Branded PDF.',
    price: 299,
    type: 'monthly_per_client',
    availableOn: ['scale', 'agency'],
    icon: 'file-text',
  },
  {
    id: 'onboarding_accelerator',
    name: 'Onboarding Accelerator',
    description: '4-session guided setup with a NEXARA specialist.',
    price: 1200,
    type: 'one_time',
    availableOn: ['growth', 'scale', 'agency'],
    icon: 'rocket',
  },
  {
    id: 'strategy_workshop',
    name: 'GTM Strategy Workshop',
    description: 'Half-day intensive GTM strategy session with a senior advisor.',
    price: 2500,
    type: 'one_time',
    availableOn: ['growth', 'scale', 'agency'],
    icon: 'target',
  },
];
