const PLANS = {
  starter: {
    id: 'starter',
    name: 'STARTER',
    displayName: 'Starter',
    color: '#6B9478',
    price: { monthly: 189, annual: 149 },
    credits: {
      included: 5000,
      rolloverMultiplier: 2,
      topUpPricePer1k: 12,
    },
    limits: {
      activeCampaigns: 2,
      teamSeats: 3,
      workspaces: 1,
      clientPortals: 0,
      customAgents: 0,
      apiCallsPerMonth: 0,
      ariaVoiceMinutes: 0,
      intentSignalAccounts: 0,
      competitorTracking: 0,
      namedAccountsABM: 0,
      whatsappMessages: 0,
    },
    agents: {
      available: ['copywriter', 'sdr', 'analytics', 'meta_monitor'],
      locked: [
        'icp_researcher', 'intent_monitor', 'competitor_intel', 'market_analyst',
        'seo', 'geo', 'social_media', 'video_script', 'brand_guardian',
        'abm_agent', 'linkedin_agent', 'whatsapp_agent', 'meta_ads',
        'google_ads', 'linkedin_ads', 'creative_intel', 'revops',
        'forecasting', 'cs_success', 'meeting_intel', 'aria_cs',
        'aria_voice',
      ],
    },
    features: {
      campaigns: true,
      campaignWizard: true,
      contentLibrary: true,
      knowledgeBase: true,
      escalationQueue: true,
      dashboard: true,
      basicAnalytics: true,
      emailOutreach: true,
      linkedinOutreach: false,
      whatsappOutreach: false,
      metaAdsManagement: false,
      metaAdsMonitoring: true,
      googleAdsManagement: false,
      linkedinAdsManagement: false,
      unifiedInbox: false,
      abmEngine: false,
      intentSignals: false,
      competitiveIntel: false,
      icpBuilder: true,
      icpScoring: false,
      predictiveForecasting: false,
      pipelineManager: false,
      customerSuccess: false,
      queryManager: false,
      calendarView: true,
      ganttPlan: false,
      clientPortal: false,
      whiteLabel: false,
      apiAccess: false,
      customAgents: false,
      verticalPlaybooks: true,
      ariaVoice: false,
      outcomeBilling: false,
      crossClientAnalytics: false,
      roleBasedAccess: false,
      subBilling: false,
      dataWarehouseSync: false,
    },
    support: {
      type: 'community',
      sla: null,
      strategyCall: false,
      dedicatedSlack: false,
      csm: false,
    },
    badge: null,
    highlight: false,
  },

  growth: {
    id: 'growth',
    name: 'GROWTH',
    displayName: 'Growth',
    color: '#3DDC84',
    price: { monthly: 599, annual: 499 },
    credits: {
      included: 25000,
      rolloverMultiplier: 2,
      topUpPricePer1k: 12,
    },
    limits: {
      activeCampaigns: -1,
      teamSeats: 10,
      workspaces: 3,
      clientPortals: 3,
      customAgents: 0,
      apiCallsPerMonth: 0,
      ariaVoiceMinutes: 0,
      intentSignalAccounts: 500,
      competitorTracking: 3,
      namedAccountsABM: 50,
      whatsappMessages: 1000,
    },
    agents: {
      available: [
        'copywriter', 'sdr', 'analytics', 'meta_monitor', 'icp_researcher',
        'intent_monitor', 'seo', 'social_media', 'brand_guardian',
        'linkedin_agent', 'meta_ads', 'google_ads', 'linkedin_ads',
        'revops', 'aria_cs',
      ],
      locked: [
        'competitor_intel', 'market_analyst', 'geo', 'video_script',
        'abm_agent', 'whatsapp_agent', 'creative_intel', 'forecasting',
        'cs_success', 'meeting_intel', 'aria_voice',
      ],
    },
    features: {
      campaigns: true,
      campaignWizard: true,
      contentLibrary: true,
      knowledgeBase: true,
      escalationQueue: true,
      dashboard: true,
      basicAnalytics: true,
      advancedAnalytics: true,
      emailOutreach: true,
      linkedinOutreach: true,
      whatsappOutreach: true,
      metaAdsManagement: true,
      metaAdsMonitoring: true,
      googleAdsManagement: true,
      linkedinAdsManagement: true,
      unifiedInbox: true,
      abmEngine: true,
      intentSignals: true,
      competitiveIntel: false,
      icpBuilder: true,
      icpScoring: true,
      predictiveForecasting: false,
      pipelineManager: true,
      customerSuccess: false,
      queryManager: true,
      calendarView: true,
      ganttPlan: true,
      clientPortal: true,
      whiteLabel: false,
      apiAccess: false,
      customAgents: false,
      verticalPlaybooks: true,
      ariaVoice: false,
      outcomeBilling: true,
      crossClientAnalytics: false,
      roleBasedAccess: true,
      subBilling: false,
      dataWarehouseSync: false,
    },
    support: {
      type: 'email',
      sla: '4h',
      strategyCall: true,
      dedicatedSlack: false,
      csm: false,
    },
    badge: 'Most Popular',
    highlight: true,
  },

  scale: {
    id: 'scale',
    name: 'SCALE',
    displayName: 'Scale',
    color: '#5EEAD4',
    price: { monthly: 1799, annual: 1499 },
    credits: {
      included: 100000,
      rolloverMultiplier: 3,
      topUpPricePer1k: 10,
    },
    limits: {
      activeCampaigns: -1,
      teamSeats: 25,
      workspaces: 10,
      clientPortals: 10,
      customAgents: 1,
      apiCallsPerMonth: 10000,
      ariaVoiceMinutes: 500,
      intentSignalAccounts: -1,
      competitorTracking: -1,
      namedAccountsABM: -1,
      whatsappMessages: -1,
    },
    agents: {
      available: [
        'copywriter', 'sdr', 'analytics', 'meta_monitor', 'icp_researcher',
        'intent_monitor', 'competitor_intel', 'market_analyst', 'seo', 'geo',
        'social_media', 'video_script', 'brand_guardian', 'abm_agent',
        'linkedin_agent', 'whatsapp_agent', 'meta_ads', 'google_ads',
        'linkedin_ads', 'creative_intel', 'revops', 'forecasting',
        'cs_success', 'meeting_intel', 'aria_cs',
      ],
      locked: ['aria_voice'],
    },
    features: {
      campaigns: true,
      campaignWizard: true,
      contentLibrary: true,
      knowledgeBase: true,
      escalationQueue: true,
      dashboard: true,
      basicAnalytics: true,
      advancedAnalytics: true,
      emailOutreach: true,
      linkedinOutreach: true,
      whatsappOutreach: true,
      metaAdsManagement: true,
      metaAdsMonitoring: true,
      googleAdsManagement: true,
      linkedinAdsManagement: true,
      unifiedInbox: true,
      abmEngine: true,
      intentSignals: true,
      competitiveIntel: true,
      icpBuilder: true,
      icpScoring: true,
      predictiveForecasting: true,
      pipelineManager: true,
      customerSuccess: true,
      queryManager: true,
      calendarView: true,
      ganttPlan: true,
      clientPortal: true,
      whiteLabel: true,
      apiAccess: true,
      customAgents: true,
      verticalPlaybooks: true,
      ariaVoice: true,
      outcomeBilling: true,
      crossClientAnalytics: false,
      roleBasedAccess: true,
      subBilling: false,
      dataWarehouseSync: true,
    },
    support: {
      type: 'slack',
      sla: '1h',
      strategyCall: true,
      dedicatedSlack: true,
      csm: false,
    },
    badge: null,
    highlight: false,
  },

  agency: {
    id: 'agency',
    name: 'AGENCY',
    displayName: 'Agency',
    color: '#A78BFA',
    price: { monthly: 4799, annual: 3999 },
    credits: {
      included: 500000,
      rolloverMultiplier: null,
      topUpPricePer1k: 8,
    },
    limits: {
      activeCampaigns: -1,
      teamSeats: -1,
      workspaces: -1,
      clientPortals: -1,
      customAgents: -1,
      apiCallsPerMonth: -1,
      ariaVoiceMinutes: -1,
      intentSignalAccounts: -1,
      competitorTracking: -1,
      namedAccountsABM: -1,
      whatsappMessages: -1,
    },
    agents: {
      available: 'all',
      locked: [],
    },
    features: {
      campaigns: true,
      campaignWizard: true,
      contentLibrary: true,
      knowledgeBase: true,
      escalationQueue: true,
      dashboard: true,
      basicAnalytics: true,
      advancedAnalytics: true,
      emailOutreach: true,
      linkedinOutreach: true,
      whatsappOutreach: true,
      metaAdsManagement: true,
      metaAdsMonitoring: true,
      googleAdsManagement: true,
      linkedinAdsManagement: true,
      unifiedInbox: true,
      abmEngine: true,
      intentSignals: true,
      competitiveIntel: true,
      icpBuilder: true,
      icpScoring: true,
      predictiveForecasting: true,
      pipelineManager: true,
      customerSuccess: true,
      queryManager: true,
      calendarView: true,
      ganttPlan: true,
      clientPortal: true,
      whiteLabel: true,
      apiAccess: true,
      customAgents: true,
      verticalPlaybooks: true,
      ariaVoice: true,
      outcomeBilling: true,
      crossClientAnalytics: true,
      roleBasedAccess: true,
      subBilling: true,
      dataWarehouseSync: true,
    },
    support: {
      type: 'dedicated_csm',
      sla: '30min',
      strategyCall: true,
      dedicatedSlack: true,
      csm: true,
    },
    badge: null,
    highlight: false,
  },
};

export function getUpgradePlan(currentPlanId) {
  const order = ['starter', 'growth', 'scale', 'agency'];
  const idx = order.indexOf(currentPlanId);
  return idx >= 0 && idx < order.length - 1 ? PLANS[order[idx + 1]] : null;
}

export function planHasFeature(planId, featureKey) {
  return PLANS[planId]?.features?.[featureKey] ?? false;
}

export function planHasAgent(planId, agentId) {
  const plan = PLANS[planId];
  if (!plan) return false;
  if (plan.agents.available === 'all') return true;
  return plan.agents.available.includes(agentId);
}

export function getPlanLimit(planId, limitKey) {
  return PLANS[planId]?.limits?.[limitKey] ?? 0;
}

export function isLimitReached(planId, limitKey, currentUsage) {
  const limit = getPlanLimit(planId, limitKey);
  if (limit === -1) return false;
  return currentUsage >= limit;
}

export { PLANS };
export const PLAN_ORDER = ['starter', 'growth', 'scale', 'agency'];
